# Generated by Django 6.0.6 on 2026-08-06 09:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB 고유 ID')),
                ('tmdb_imdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IMDb ID (tt1234567)')),
                ('tmdb_title', models.CharField(max_length=255, verbose_name='TMDB 영화 제목')),
                ('tmdb_original_title', models.CharField(blank=True, default='', max_length=255, verbose_name='TMDB 원제')),
                ('translated_title', models.CharField(blank=True, default='', max_length=255, verbose_name='AI 번역 제목')),
                ('tmdb_genre', models.CharField(blank=True, default='', max_length=255, verbose_name='TMDB 장르')),
                ('tmdb_release_date', models.DateField(blank=True, null=True, verbose_name='TMDB 개봉일')),
                ('tmdb_release_date_kr', models.DateField(blank=True, null=True, verbose_name='TMDB 국내 개봉일')),
                ('tmdb_runtime', models.IntegerField(default=0, verbose_name='TMDB 상영시간(분)')),
                ('tmdb_rating', models.FloatField(default=0.0, verbose_name='TMDB 평점')),
                ('tmdb_vote_count', models.IntegerField(default=0, verbose_name='TMDB 평가 투표수')),
                ('tmdb_overview', models.TextField(blank=True, default='', verbose_name='TMDB 줄거리')),
                ('tmdb_poster_url', models.URLField(blank=True, default='', max_length=500, verbose_name='TMDB 포스터 이미지 URL')),
                ('backdrop_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='TMDB 가로 배경 이미지 경로')),
                ('tmdb_trailer_url', models.URLField(blank=True, default='', max_length=500, verbose_name='TMDB 공식 예고편 URL')),
                ('tmdb_director', models.CharField(blank=True, default='', max_length=255, verbose_name='TMDB 감독 이름')),
                ('tmdb_director_id', models.IntegerField(blank=True, null=True, verbose_name='TMDB 감독 고유 ID')),
                ('tmdb_director_image_url', models.URLField(blank=True, default='', max_length=500, verbose_name='TMDB 감독 사진 URL')),
                ('tmdb_screenwriter', models.CharField(blank=True, default='', max_length=255, verbose_name='TMDB 각본가')),
                ('tmdb_screenwriter_id', models.IntegerField(blank=True, null=True, verbose_name='TMDB 각본가 고유 ID')),
                ('tmdb_actors', models.TextField(blank=True, default='', verbose_name='TMDB 상위 출연진 (단순 문자열)')),
                ('tmdb_actor_details', models.JSONField(blank=True, default=list, verbose_name='TMDB 출연진 상세 (JSON)')),
                ('tmdb_streaming_providers', models.JSONField(blank=True, default=list, verbose_name='TMDB 스트리밍 OTT 정보 (JSON)')),
                ('tmdb_recommended_movies', models.JSONField(blank=True, default=list, verbose_name='TMDB 추천 유사 영화 (JSON)')),
                ('tmdb_keywords', models.TextField(blank=True, default='', verbose_name='TMDB 연관 키워드')),
                ('tmdb_certification_kr', models.CharField(blank=True, default='', max_length=50, verbose_name='TMDB 국내 관람 등급')),
                ('tmdb_certification_us', models.CharField(blank=True, default='', max_length=50, verbose_name='TMDB 미국 관람 등급')),
                ('tmdb_budget', models.BigIntegerField(default=0, verbose_name='TMDB 제작 예산 ($)')),
                ('tmdb_revenue', models.BigIntegerField(default=0, verbose_name='TMDB 흥행 수익 ($)')),
                ('tmdb_production_country_code', models.CharField(blank=True, default='', max_length=50, verbose_name='TMDB 국가 코드 (ISO)')),
                ('tmdb_production_country_eng', models.CharField(blank=True, default='', max_length=200, verbose_name='TMDB 영문 국가명')),
                ('tmdb_production_country_kr', models.CharField(blank=True, default='', max_length=200, verbose_name='TMDB 한글 국가명')),
                ('imdb_rating', models.FloatField(blank=True, default=0.0, null=True, verbose_name='IMDb 평점')),
                ('imdb_vote_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='IMDb 평가 투표수')),
                ('imdb_runtime', models.IntegerField(blank=True, default=0, null=True, verbose_name='IMDb 상영시간(분)')),
                ('imdb_genre', models.CharField(blank=True, default='', max_length=255, verbose_name='IMDb 장르')),
                ('imdb_release_date', models.CharField(blank=True, default='', max_length=20, verbose_name='IMDb 개봉 연도')),
                ('youtube_trailer_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='유튜브 자체 검색 예고편 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DB 최초 저장일')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='DB 최종 수정일')),
            ],
        ),
        migrations.CreateModel(
            name='TvSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB 고유 ID')),
                ('tmdb_imdb_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='IMDb ID (tt1234567)')),
                ('tmdb_title', models.CharField(max_length=255, verbose_name='TMDB 시리즈 제목')),
                ('tmdb_original_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB 원제')),
                ('translated_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='AI 번역 제목')),
                ('tmdb_genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB 장르')),
                ('tmdb_release_date', models.DateField(blank=True, null=True, verbose_name='TMDB 방영 시작일')),
                ('tmdb_runtime', models.IntegerField(default=0, verbose_name='TMDB 에피소드 평균 상영시간(분)')),
                ('tmdb_rating', models.FloatField(default=0.0, verbose_name='TMDB 평점')),
                ('tmdb_vote_count', models.IntegerField(default=0, verbose_name='TMDB 평가 투표수')),
                ('tmdb_overview', models.TextField(blank=True, null=True, verbose_name='TMDB 줄거리')),
                ('tmdb_poster_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='TMDB 포스터 이미지 URL')),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB 가로 배경 이미지 경로')),
                ('tmdb_trailer_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='TMDB 공식 예고편 URL')),
                ('tmdb_director', models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB 총괄 프로듀서/감독')),
                ('tmdb_director_id', models.IntegerField(blank=True, null=True, verbose_name='TMDB 감독 고유 ID')),
                ('tmdb_director_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='TMDB 감독 사진 URL')),
                ('tmdb_screenwriter', models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB 각본가')),
                ('tmdb_screenwriter_id', models.IntegerField(blank=True, null=True, verbose_name='TMDB 각본가 고유 ID')),
                ('tmdb_actors', models.CharField(blank=True, max_length=500, null=True, verbose_name='TMDB 상위 출연진 (단순 문자열)')),
                ('tmdb_actor_details', models.JSONField(blank=True, default=list, null=True, verbose_name='TMDB 출연진 상세 (JSON)')),
                ('tmdb_streaming_providers', models.JSONField(blank=True, default=list, null=True, verbose_name='TMDB 스트리밍 OTT 정보 (JSON)')),
                ('tmdb_recommended_movies', models.JSONField(blank=True, default=list, null=True, verbose_name='TMDB 추천 유사 드라마 (JSON)')),
                ('tmdb_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='TMDB 연관 키워드')),
                ('tmdb_certification_kr', models.CharField(blank=True, max_length=50, null=True, verbose_name='TMDB 국내 관람 등급')),
                ('tmdb_certification_us', models.CharField(blank=True, max_length=50, null=True, verbose_name='TMDB 미국 관람 등급')),
                ('tmdb_budget', models.BigIntegerField(default=0, verbose_name='TMDB 제작 예산 ($)')),
                ('tmdb_revenue', models.BigIntegerField(default=0, verbose_name='TMDB 흥행 수익 ($)')),
                ('tmdb_production_country_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='TMDB 국가 코드 (ISO)')),
                ('tmdb_production_country_eng', models.CharField(blank=True, max_length=100, null=True, verbose_name='TMDB 영문 국가명')),
                ('tmdb_production_country_kr', models.CharField(blank=True, max_length=100, null=True, verbose_name='TMDB 한글 국가명')),
                ('tmdb_number_of_seasons', models.IntegerField(blank=True, default=0, null=True, verbose_name='TMDB 총 시즌 수')),
                ('tmdb_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='TMDB 방영 상태 (완결/방영중)')),
                ('seasons_data', models.JSONField(blank=True, null=True, verbose_name='TMDB 시즌별 상세 정보 (JSON)')),
                ('imdb_rating', models.FloatField(db_index=True, default=0.0, verbose_name='IMDb 평점')),
                ('imdb_vote_count', models.IntegerField(db_index=True, default=0, verbose_name='IMDb 평가 투표수')),
                ('imdb_runtime', models.IntegerField(default=0, verbose_name='IMDb 평균 상영시간(분)')),
                ('imdb_genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='IMDb 장르')),
                ('imdb_release_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMDb 방영 시작 연도')),
                ('youtube_trailer_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='유튜브 자체 검색 예고편 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DB 최초 저장일')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='DB 최종 수정일')),
            ],
            options={
                'db_table': 'tv_series',
                'ordering': ['-imdb_vote_count', '-tmdb_release_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)], verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 평가일')),
                ('review', models.TextField(blank=True, null=True, verbose_name='감상평')),
                ('is_public', models.BooleanField(default=True, verbose_name='전체 공개 여부')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('movie', models.ForeignKey(blank=True, db_column='movie_tmdb_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='movie.movie', to_field='tmdb_id', verbose_name='평가한 영화')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('tvseries', models.ForeignKey(blank=True, db_column='tvseries_tmdb_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratings', to='movie.tvseries', to_field='tmdb_id', verbose_name='평가한 TV 시리즈')),
            ],
            options={
                'verbose_name': '사용자 평점',
                'verbose_name_plural': '사용자 평점 목록',
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_rating'), models.UniqueConstraint(fields=('user', 'tvseries'), name='unique_user_tvseries_rating')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='담은 날짜')),
                ('movie', models.ForeignKey(blank=True, db_column='movie_tmdb_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watchlisted_by', to='movie.movie', to_field='tmdb_id', verbose_name='찜한 영화')),
                ('tvseries', models.ForeignKey(blank=True, db_column='tvseries_tmdb_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='watchlisted_by', to='movie.tvseries', to_field='tmdb_id', verbose_name='찜한 TV 시리즈')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '찜한 작품',
                'verbose_name_plural': '찜한 작품 목록',
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_watchlist'), models.UniqueConstraint(fields=('user', 'tvseries'), name='unique_user_tvseries_watchlist')],
            },
        ),
    ]
