# Generated by Django 6.0.6 on 2026-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_adult_content',
            field=models.BooleanField(default=False),
        ),
    ]
