# Generated by Django 6.0.6 on 2026-08-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_is_adult_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TMDB 가로 배경 URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_vote_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='IMDb 평가수'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_certification_kr',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='TMDB KR등급'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_certification_us',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='TMDB US등급'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_director',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='TMDB 감독'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IMDb ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_poster_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='TMDB 포스터 URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_recommended_movies',
            field=models.JSONField(blank=True, default=list, verbose_name='TMDB 추천/유사 영화 (JSON)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_release_date_kr',
            field=models.DateField(blank=True, null=True, verbose_name='TMDB K개봉일'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_streaming_providers',
            field=models.JSONField(blank=True, default=list, verbose_name='TMDB OTT 정보(JSON)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_vote_count',
            field=models.IntegerField(default=0, verbose_name='TMDB 평가수'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB 가로 배경 URL'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='imdb_vote_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='IMDb 평가수'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_certification_kr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TMDB KR등급'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_certification_us',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TMDB US등급'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDB ID'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_imdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='IMDb ID'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_poster_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='TMDB 포스터 URL'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_recommended_movies',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='TMDB 추천/유사 드라마 (JSON)'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_streaming_providers',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='TMDB OTT 정보 (JSON)'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_vote_count',
            field=models.IntegerField(default=0, verbose_name='TMDB 평가수'),
        ),
    ]
