# Generated by Django 6.0.6 on 2026-08-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_original_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='원어'),
        ),
        migrations.AddField(
            model_name='tvseries',
            name='tmdb_original_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='원어'),
        ),
    ]
