# Generated by Django 6.0.6 on 2026-08-20 11:02

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_tmdb_original_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTrailerReport',
            fields=[
            ],
            options={
                'verbose_name': '🎬 영화별 예고편 오류 현황',
                'verbose_name_plural': '🎬 영화별 예고편 오류 현황',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movie.movie',),
        ),
        migrations.CreateModel(
            name='TvTrailerReport',
            fields=[
            ],
            options={
                'verbose_name': '📺 시리즈별 예고편 오류 현황',
                'verbose_name_plural': '📺 시리즈별 예고편 오류 현황',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movie.tvseries',),
        ),
        migrations.CreateModel(
            name='UserTrailerReport',
            fields=[
            ],
            options={
                'verbose_name': '👤 유저별 신고 랭킹 (예고편 오류)',
                'verbose_name_plural': '👤 유저별 신고 랭킹 (예고편 오류)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movie.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TrailerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_reports', to='movie.movie')),
                ('tvseries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailer_reports', to='movie.tvseries')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailer_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '예고편 오류 신고',
                'verbose_name_plural': '예고편 오류 신고 목록',
            },
        ),
    ]
