# Generated by Django 6.0.6 on 2026-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movietrailerreport_tvtrailerreport_usertrailerreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_certification_kr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='TMDB KR등급'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_certification_us',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='TMDB US등급'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_original_language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='원어'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_production_country_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='TMDB 국가 코드 (ISO)'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='imdb_release_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IMDb 방영 시작 연도'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_certification_kr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB KR등급'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_certification_us',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB US등급'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_original_language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='원어'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_production_country_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB 국가 코드 (ISO)'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TMDB 방영 상태 (완결/방영중)'),
        ),
    ]
