# Generated by Django 6.0.6 on 2026-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_tmdb_certification_kr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='TMDB 가로 배경 URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_production_country_eng',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='TMDB 영문 국가명'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_production_country_kr',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='TMDB 한글 국가명'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='backdrop_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='TMDB 가로 배경 URL'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_production_country_eng',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='TMDB 영문 국가명'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tmdb_production_country_kr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='TMDB 한글 국가명'),
        ),
    ]
